name: 'fuel_analytics'
version: '1.0.0'
config-version: 2

profile: 'fuel_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"


models:
  fuel_analytics:

    staging:
      +materialized: view
      +schema: bronze

    intermediate:
      +materialized: table
      +schema: silver

    marts:
      +materialized: table
      +schema: gold

    reporting:
      +materialized: table
      +schema: gold


seeds:
  fuel_analytics:
    +schema: bronze


snapshots:
  fuel_analytics:
    +target_schema: silver